In [1]:
import pandas as pd
import numpy as np

In [2]:
olist_path = "../data/olist_spending_dataset.csv"

olist_df = pd.read_csv(olist_path)

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [4]:
print("Number of rows:", olist_df.shape[0])
print("Number of columns:", olist_df.shape[1])
print("Columns:")
print(olist_df.columns.tolist())

Number of rows: 99441
Number of columns: 22
Columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'customer_unique_id', 'customer_city', 'customer_state', 'number_of_items', 'number_of_products', 'number_of_sellers', 'total_item_price', 'total_freight_value', 'payment_value', 'payment_installments', 'payment_type', 'purchase_year', 'purchase_month', 'purchase_dayofweek']

In [5]:
olist_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_city,...,number_of_products,number_of_sellers,total_item_price,total_freight_value,payment_value,payment_installments,payment_type,purchase_year,purchase_month,purchase_dayofweek
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,sao paulo,...,1.0,1.0,29.99,8.72,38.71,1.0,credit_card|voucher,2017,10,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,barreiras,...,1.0,1.0,118.70,22.76,141.46,1.0,boleto,2018,7,1
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,...,1.0,1.0,159.90,19.22,179.12,3.0,credit_card,2018,8,2
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,...,1.0,1.0,45.00,27.20,72.20,1.0,credit_card,2017,11,5
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,...,1.0,1.0,19.90,8.72,28.62,1.0,credit_card,2018,2,1

In [6]:
olist_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
 8   customer_unique_id             99441 non-null  object
 9   customer_city                  99441 non-null  object
 10  customer_state                 99441 non-null  object
 11  number_of_items                98666 non-null  float64
 12  number_of_products             98666 non-null  float64
 13  number_of_sellers              98666 non-null  float64
 14  total_item_price               98666 non-null  float64
 15  total_freight_value            98666 non-null  float64
 16  payment_value                  99440 non-null  float64
 17  payment_installments           99440 non-null  float64
 18  payment_type                   99440 non-null  object
 19  purchase_year                  99441 non-null  int64
 20  purchase_month                 99441 non-null  int64
 21  purchase_dayofweek             99441 non-null  int64
dtypes: float64(7), int64(3), object(12)
memory usage: 16.7+ MB

In [7]:
missing_values = olist_df.isnull().sum()
print(missing_values)

missing_percentage = (
    olist_df.isnull().sum() / len(olist_df) * 100
)
print(missing_percentage.round(2))

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
customer_unique_id                  0
customer_city                       0
customer_state                      0
number_of_items                   775
number_of_products                775
number_of_sellers                 775
total_item_price                  775
total_freight_value               775
payment_value                       1
payment_installments                1
payment_type                        1
purchase_year                       0
purchase_month                      0
purchase_dayofweek                  0
dtype: int64
order_id                         0.00
customer_id                      0.00
order_status                     0.00
order_purchase_timestamp         0.00
order_approved_at                0.16
order_delivered_carrier_date     1.79
order_delivered_customer_date    2.98
order_estimated_delivery_date    0.00
customer_unique_id               0.00
customer_city                    0.00
customer_state                   0.00
number_of_items                  0.78
number_of_products               0.78
number_of_sellers                0.78
total_item_price                 0.78
total_freight_value              0.78
payment_value                    0.00
payment_installments             0.00
payment_type                     0.00
purchase_year                    0.00
purchase_month                   0.00
purchase_dayofweek               0.00
dtype: float64

In [8]:
duplicate_count = olist_df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [9]:
print(
    "Unique customers:",
    olist_df["customer_unique_id"].nunique()
)

print(
    "Unique orders:",
    olist_df["order_id"].nunique()
)

Unique customers: 96096
Unique orders: 99441

In [10]:
print(
    olist_df["order_status"]
    .value_counts()
)
print(
    olist_df["order_status"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64
order_status
delivered      97.02
shipped         1.11
canceled        0.63
unavailable     0.61
invoiced        0.32
processing      0.30
created         0.01
approved        0.00
Name: proportion, dtype: float64

In [11]:
olist_df[
    [
        "number_of_items",
        "number_of_products",
        "number_of_sellers",
        "total_item_price",
        "total_freight_value",
        "payment_value",
        "payment_installments"
    ]
].describe()

,number_of_items,number_of_products,number_of_sellers,total_item_price,total_freight_value,payment_value,payment_installments
count,98666.000000,98666.000000,98666.000000,98666.000000,98666.000000,99440.000000,99440.000000
mean,1.141731,1.038098,1.013622,137.754076,22.823562,160.990267,2.930521
std,0.538452,0.226456,0.122297,210.645145,21.650909,221.951257,2.715685
min,1.000000,1.000000,1.000000,0.850000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,1.000000,45.900000,13.850000,62.010000,1.000000
50%,1.000000,1.000000,1.000000,86.900000,17.170000,105.290000,2.000000
75%,1.000000,1.000000,1.000000,149.900000,24.040000,176.970000,4.000000
max,21.000000,8.000000,5.000000,13440.000000,1794.960000,13664.080000,24.000000

In [12]:
print(
    "Payment value <= 0:",
    (olist_df["payment_value"] <= 0).sum()
)

print(
    "Item price < 0:",
    (olist_df["total_item_price"] < 0).sum()
)

print(
    "Freight value < 0:",
    (olist_df["total_freight_value"] < 0).sum()
)

Payment value <= 0: 3
Item price < 0: 0
Freight value < 0: 0

In [13]:
olist_df["order_purchase_timestamp"] = pd.to_datetime(
    olist_df["order_purchase_timestamp"],
    errors="coerce"
)
print(
    olist_df["order_purchase_timestamp"].dtype
)

datetime64[ns]

In [14]:
print(
    "Purchase date range:"
)

print(
    olist_df["order_purchase_timestamp"].min(),
    "to",
    olist_df["order_purchase_timestamp"].max()
)

Purchase date range:
2016-09-04 21:15:19 to 2018-10-17 17:30:18

In [15]:
print(
    "Missing customer IDs:",
    olist_df["customer_unique_id"].isnull().sum()
)
print(
    "Empty customer IDs:",
    (
        olist_df["customer_unique_id"]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )
)

Missing customer IDs: 0
Empty customer IDs: 0

In [16]:
olist_df["calculated_order_value"] = (
    olist_df["total_item_price"]
    + olist_df["total_freight_value"]
)

difference = (
    olist_df["payment_value"]
    - olist_df["calculated_order_value"]
).abs()

print(
    "Maximum absolute difference:",
    difference.max()
)

print(
    "Rows with difference greater than 0.01:",
    (difference > 0.01).sum()
)

Maximum absolute difference: 182.80999999999995
Rows with difference greater than 0.01: 378

In [17]:
olist_clean = olist_df.copy()
olist_clean = olist_clean.dropna(
    subset=["customer_unique_id"]
).copy()
olist_clean = olist_clean.dropna(
    subset=["order_purchase_timestamp"]
).copy()
olist_clean = olist_clean[
    olist_clean["payment_value"] > 0
].copy()

In [18]:
order_counts = (
    olist_clean["order_id"]
    .value_counts()
)

print(
    "Orders appearing more than once:",
    (order_counts > 1).sum()
)

Orders appearing more than once: 0

In [19]:
print(
    olist_clean["order_id"].duplicated().sum()
)

0

In [20]:
print(
    olist_clean["order_status"]
    .value_counts()
)
delivered_count = (
    olist_clean["order_status"]
    .eq("delivered")
    .sum()
)

print("Delivered orders:", delivered_count)
print(
    "Delivered percentage:",
    round(
        delivered_count / len(olist_clean) * 100,
        2
    )
)

order_status
delivered      96477
shipped         1107
canceled         622
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64
Delivered orders: 96477
Delivered percentage: 97.02

In [21]:
olist_clean = olist_clean.drop(
    columns=["calculated_order_value"],
    errors="ignore"
)
print("Original shape:", olist_df.shape)
print("Cleaned shape:", olist_clean.shape)

Original shape: (99441, 23)
Cleaned shape: (99437, 22)

In [22]:
print(
    "\nMissing customer IDs:",
    olist_clean["customer_unique_id"].isnull().sum()
)

print(
    "Missing purchase dates:",
    olist_clean["order_purchase_timestamp"].isnull().sum()
)

print(
    "Non-positive payment values:",
    (olist_clean["payment_value"] <= 0).sum()
)

Missing customer IDs: 0
Missing purchase dates: 0
Non-positive payment values: 0

In [23]:
print(
    "Cleaned purchase date range:"
)

print(
    olist_clean["order_purchase_timestamp"].min(),
    "to",
    olist_clean["order_purchase_timestamp"].max()
)

Cleaned purchase date range:
2016-09-04 21:15:19 to 2018-10-17 17:30:18

In [24]:
print(
    "Unique customers:",
    olist_clean["customer_unique_id"].nunique()
)

print(
    "Unique orders:",
    olist_clean["order_id"].nunique()
)

Unique customers: 96093
Unique orders: 99437

In [25]:
olist_clean_path = "../data/olist_spending_cleaned.csv"

olist_clean.to_csv(
    olist_clean_path,
    index=False
)

print("Cleaned Olist dataset saved to:")
print(olist_clean_path)

Cleaned Olist dataset saved to:
../data/olist_spending_cleaned.csv

In [26]:
print(olist_df.isnull().sum())

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
customer_unique_id                  0
customer_city                       0
customer_state                      0
number_of_items                   775
number_of_products                775
number_of_sellers                 775
total_item_price                  775
total_freight_value               775
payment_value                       1
payment_installments                1
payment_type                        1
purchase_year                       0
purchase_month                      0
purchase_dayofweek                  0
calculated_order_value            775
dtype: int64

In [27]:
print(olist_df["order_status"].value_counts())

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [28]:
print(
    olist_df["order_purchase_timestamp"].min(),
    olist_df["order_purchase_timestamp"].max()
)

2016-09-04 21:15:19 2018-10-17 17:30:18

In [29]:
print(
    olist_clean.shape,
    olist_clean["customer_unique_id"].nunique(),
    olist_clean["order_id"].nunique()
)

(99437, 22) 96093 99437

In [30]:
print(
    "Rows with difference > 0.01:",
    (difference > 0.01).sum()
)

Rows with difference > 0.01: 378

# Task 5 - Construct Spending Features + Target

In [31]:
max_olist_date = olist_clean["order_purchase_timestamp"].max()

spending_observation_end = (
    max_olist_date - pd.Timedelta(days=90)
)

print("Maximum purchase date:", max_olist_date)
print(
    "Spending observation period ends:",
    spending_observation_end
)

Maximum purchase date: 2018-10-17 17:30:18
Spending observation period ends: 2018-07-19 17:30:18

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18256\2741732742.py:4: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  max_olist_date - pd.Timedelta(days=90)

In [32]:
olist_model = olist_clean[
    olist_clean["order_status"] == "delivered"
].copy()

print("Delivered orders:", len(olist_model))
print(
    "Unique customers:",
    olist_model["customer_unique_id"].nunique()
)

Delivered orders: 96477
Unique customers: 93357

In [33]:
print(
    olist_model.isnull().sum()
)

order_id                          0
customer_id                       0
order_status                      0
order_purchase_timestamp          0
order_approved_at                14
order_delivered_carrier_date      2
order_delivered_customer_date     8
order_estimated_delivery_date     0
customer_unique_id                0
customer_city                     0
customer_state                    0
number_of_items                   0
number_of_products                0
number_of_sellers                 0
total_item_price                  0
total_freight_value               0
payment_value                     0
payment_installments              0
payment_type                      0
purchase_year                     0
purchase_month                    0
purchase_dayofweek                0
dtype: int64

In [34]:
required_columns = [
    "customer_unique_id",
    "order_purchase_timestamp",
    "payment_value",
    "number_of_items",
    "number_of_products",
    "number_of_sellers",
    "total_item_price",
    "total_freight_value",
    "payment_installments"
]

olist_model = olist_model.dropna(
    subset=required_columns
).copy()

In [35]:
print(
    "Rows after removing incomplete modelling records:",
    len(olist_model)
)

Rows after removing incomplete modelling records: 96477

In [36]:
historical_olist = olist_model[
    olist_model["order_purchase_timestamp"]
    <= spending_observation_end
].copy()

In [37]:
future_olist = olist_model[
    olist_model["order_purchase_timestamp"]
    > spending_observation_end
].copy()

In [38]:
print(
    "Historical orders:",
    len(historical_olist)
)

print(
    "Future orders:",
    len(future_olist)
)

Historical orders: 87193
Future orders: 9284

In [39]:
print(
    "Historical period:",
    historical_olist["order_purchase_timestamp"].min(),
    "to",
    historical_olist["order_purchase_timestamp"].max()
)

print(
    "Future period:",
    future_olist["order_purchase_timestamp"].min(),
    "to",
    future_olist["order_purchase_timestamp"].max()
)

Historical period: 2016-10-03 09:44:50 to 2018-07-19 17:24:35
Future period: 2018-07-19 17:31:45 to 2018-08-29 15:00:37

In [40]:
historical_olist["OrderValue"] = (
    historical_olist["payment_value"]
)
future_olist["FutureOrderValue"] = (
    future_olist["payment_value"]
)

In [41]:
customer_last_purchase = (
    historical_olist
    .groupby("customer_unique_id")["order_purchase_timestamp"]
    .max()
)
recency = (
    spending_observation_end
    - customer_last_purchase
).dt.days

In [42]:
recency = (
    recency
    .rename("Recency")
    .reset_index()
)

In [43]:
frequency = (
    historical_olist
    .groupby("customer_unique_id")["order_id"]
    .nunique()
    .rename("Frequency")
    .reset_index()
)

In [44]:
monetary = (
    historical_olist
    .groupby("customer_unique_id")["OrderValue"]
    .sum()
    .rename("HistoricalSpending")
    .reset_index()
)

In [45]:
total_items = (
    historical_olist
    .groupby("customer_unique_id")["number_of_items"]
    .sum()
    .rename("TotalItems")
    .reset_index()
)

In [46]:
total_products = (
    historical_olist
    .groupby("customer_unique_id")["number_of_products"]
    .sum()
    .rename("TotalProducts")
    .reset_index()
)

In [47]:
total_sellers = (
    historical_olist
    .groupby("customer_unique_id")["number_of_sellers"]
    .sum()
    .rename("TotalSellers")
    .reset_index()
)

In [48]:
average_order_value = monetary.copy()

average_order_value["AverageOrderValue"] = (
    average_order_value["HistoricalSpending"]
    / frequency["Frequency"]
)

average_order_value = average_order_value[
    [
        "customer_unique_id",
        "AverageOrderValue"
    ]
]

In [49]:
average_freight = (
    historical_olist
    .groupby("customer_unique_id")["total_freight_value"]
    .mean()
    .rename("AverageFreightValue")
    .reset_index()
)

In [50]:
average_installments = (
    historical_olist
    .groupby("customer_unique_id")["payment_installments"]
    .mean()
    .rename("AverageInstallments")
    .reset_index()
)

In [51]:
spending_features = recency.copy()
spending_features = spending_features.merge(
    frequency,
    on="customer_unique_id",
    how="left"
)

spending_features = spending_features.merge(
    monetary,
    on="customer_unique_id",
    how="left"
)

spending_features = spending_features.merge(
    total_items,
    on="customer_unique_id",
    how="left"
)

spending_features = spending_features.merge(
    total_products,
    on="customer_unique_id",
    how="left"
)

spending_features = spending_features.merge(
    total_sellers,
    on="customer_unique_id",
    how="left"
)

spending_features = spending_features.merge(
    average_order_value,
    on="customer_unique_id",
    how="left"
)

spending_features = spending_features.merge(
    average_freight,
    on="customer_unique_id",
    how="left"
)

spending_features = spending_features.merge(
    average_installments,
    on="customer_unique_id",
    how="left"
)

In [52]:
future_spending = (
    future_olist
    .groupby("customer_unique_id")["FutureOrderValue"]
    .sum()
    .rename("FutureSpending")
    .reset_index()
)

In [53]:
spending_features = spending_features.merge(
    future_spending,
    on="customer_unique_id",
    how="left"
)

In [54]:
spending_features["FutureSpending"] = (
    spending_features["FutureSpending"]
    .fillna(0)
)

In [55]:
spending_features.head()

,customer_unique_id,Recency,Frequency,HistoricalSpending,TotalItems,TotalProducts,TotalSellers,AverageOrderValue,AverageFreightValue,AverageInstallments,FutureSpending
0,0000366f3b9a7992bf8c76cfdf3221e2,70,1,141.90,1.0,1.0,1.0,141.90,12.00,8.0,0.0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,73,1,27.19,1.0,1.0,1.0,27.19,8.29,1.0,0.0
2,0000f46a3911fa3c0805444483337064,495,1,86.22,1.0,1.0,1.0,86.22,17.22,8.0,0.0
3,0000f6ccb0745a6a4b88665a16c9f078,279,1,43.62,1.0,1.0,1.0,43.62,17.63,4.0,0.0
4,0004aac84e0df4da2b147fca70cf8255,246,1,196.89,1.0,1.0,1.0,196.89,16.89,6.0,0.0

In [56]:
print(
    "Customer feature dataset shape:",
    spending_features.shape
)

Customer feature dataset shape: (84378, 11)

In [57]:
spending_features.columns.tolist()

['customer_unique_id',
 'Recency',
 'Frequency',
 'HistoricalSpending',
 'TotalItems',
 'TotalProducts',
 'TotalSellers',
 'AverageOrderValue',
 'AverageFreightValue',
 'AverageInstallments',
 'FutureSpending']

In [58]:
print(
    spending_features["FutureSpending"].describe()
)

count    84378.000000
mean         0.372877
std         11.064015
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       1596.960000
Name: FutureSpending, dtype: float64

In [59]:
print(
    "Customers with zero future spending:",
    (
        spending_features["FutureSpending"] == 0
    ).sum()
)

Customers with zero future spending: 84156

In [60]:
print(
    "Percentage with zero future spending:",
    round(
        (
            spending_features["FutureSpending"] == 0
        ).mean() * 100,
        2
    )
)

Percentage with zero future spending: 99.74

In [61]:
spending_features.isnull().sum()

customer_unique_id     0
Recency                0
Frequency              0
HistoricalSpending     0
TotalItems             0
TotalProducts          0
TotalSellers           0
AverageOrderValue      0
AverageFreightValue    0
AverageInstallments    0
FutureSpending         0
dtype: int64

In [62]:
spending_features.describe()

,Recency,Frequency,HistoricalSpending,TotalItems,TotalProducts,TotalSellers,AverageOrderValue,AverageFreightValue,AverageInstallments,FutureSpending
count,84378.000000,84378.000000,84378.000000,84378.000000,84378.000000,84378.000000,84378.000000,84378.000000,84378.000000,84378.000000
mean,219.470004,1.033362,165.378779,1.181493,1.072673,1.047109,160.524848,22.665947,2.934569,0.372877
std,142.183871,0.206817,225.369586,0.620689,0.324015,0.246712,218.911398,21.437337,2.706407,11.064015
min,0.000000,1.000000,10.070000,1.000000,1.000000,1.000000,10.070000,0.000000,0.000000,0.000000
25%,103.000000,1.000000,63.110000,1.000000,1.000000,1.000000,62.440000,13.930000,1.000000,0.000000
50%,197.000000,1.000000,107.920000,1.000000,1.000000,1.000000,105.800000,17.070000,2.000000,0.000000
75%,322.000000,1.000000,182.830000,1.000000,1.000000,1.000000,176.717500,24.050000,4.000000,0.000000
max,654.000000,11.000000,13664.080000,21.000000,13.000000,11.000000,13664.080000,1794.960000,24.000000,1596.960000

In [63]:
print(spending_features.shape)

(84378, 11)

In [64]:
print(
    spending_features["FutureSpending"].describe()
)

count    84378.000000
mean         0.372877
std         11.064015
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       1596.960000
Name: FutureSpending, dtype: float64

In [65]:
print(
    "Customers with zero future spending:",
    (spending_features["FutureSpending"] == 0).sum()
)

Customers with zero future spending: 84156

In [66]:
spending_features.isnull().sum()

customer_unique_id     0
Recency                0
Frequency              0
HistoricalSpending     0
TotalItems             0
TotalProducts          0
TotalSellers           0
AverageOrderValue      0
AverageFreightValue    0
AverageInstallments    0
FutureSpending         0
dtype: int64

# Task 6.0 Fixing errors

In [67]:
max_olist_date = olist_model["order_purchase_timestamp"].max()

print("Maximum Olist purchase date:", max_olist_date)

Maximum Olist purchase date: 2018-08-29 15:00:37

In [68]:
def evaluate_future_window(days):
    cutoff = max_olist_date - pd.Timedelta(days=days)

    historical = olist_model[
        olist_model["order_purchase_timestamp"] <= cutoff
    ]

    future = olist_model[
        olist_model["order_purchase_timestamp"] > cutoff
    ]

    historical_customers = historical["customer_unique_id"].unique()

    future_spending = (
        future
        .groupby("customer_unique_id")["payment_value"]
        .sum()
    )

    future_spending = future_spending.reindex(
        historical_customers,
        fill_value=0
    )

    positive_customers = (future_spending > 0).sum()
    total_customers = len(future_spending)
    zero_customers = (future_spending == 0).sum()

    return {
        "Future Window (Days)": days,
        "Cutoff Date": cutoff,
        "Historical Customers": total_customers,
        "Positive Future Spending": positive_customers,
        "Zero Future Spending": zero_customers,
        "Positive %": round(
            positive_customers / total_customers * 100,
            2
        ),
        "Zero %": round(
            zero_customers / total_customers * 100,
            2
        )
    }

In [69]:
window_results = pd.DataFrame([
    evaluate_future_window(90),
    evaluate_future_window(120),
    evaluate_future_window(180),
    evaluate_future_window(270),
    evaluate_future_window(365)
])

window_results

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18256\1695833251.py:2: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  cutoff = max_olist_date - pd.Timedelta(days=days)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18256\1695833251.py:2: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  cutoff = max_olist_date - pd.Timedelta(days=days)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18256\1695833251.py:2: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  cutoff = max_olist_date - pd.Timedelta(days=days)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18256\1695833251.py:2: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  cutoff = max_olist_date - pd.Timedelta(days=days)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18256\1695833251.py:2: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  cutoff = max_olist_date - pd.Timedelta(days=days)

,Future Window (Days),Cutoff Date,Historical Customers,Positive Future Spending,Zero Future Spending,Positive %,Zero %
0,90,2018-05-31 15:00:37,75319,421,74898,0.56,99.44
1,120,2018-05-01 15:00:37,68976,539,68437,0.78,99.22
2,180,2018-03-02 15:00:37,55906,655,55251,1.17,98.83
3,270,2017-12-02 15:00:37,37408,666,36742,1.78,98.22
4,365,2017-08-29 15:00:37,21287,550,20737,2.58,97.42

In [70]:
print(
    window_results[
        [
            "Future Window (Days)",
            "Historical Customers",
            "Positive Future Spending",
            "Positive %",
            "Zero %"
        ]
    ]
)

   Future Window (Days)  Historical Customers  Positive Future Spending  \
0                    90                 75319                       421
1                   120                 68976                       539
2                   180                 55906                       655
3                   270                 37408                       666
4                   365                 21287                       550

   Positive %  Zero %
0        0.56   99.44
1        0.78   99.22
2        1.17   98.83
3        1.78   98.22
4        2.58   97.42

In [71]:
def future_spending_distribution(days):
    cutoff = max_olist_date - pd.Timedelta(days=days)

    historical = olist_model[
        olist_model["order_purchase_timestamp"] <= cutoff
    ]

    future = olist_model[
        olist_model["order_purchase_timestamp"] > cutoff
    ]

    historical_customers = historical["customer_unique_id"].unique()

    future_spending = (
        future
        .groupby("customer_unique_id")["payment_value"]
        .sum()
        .reindex(historical_customers, fill_value=0)
    )

    return future_spending

In [72]:
future_180 = future_spending_distribution(180)

print(future_180.describe())

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18256\506006491.py:2: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  cutoff = max_olist_date - pd.Timedelta(days=days)

count    55906.000000
mean         1.875351
std         24.858519
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       1596.960000
Name: payment_value, dtype: float64

In [73]:
print(
    "Positive customers:",
    (future_180 > 0).sum()
)

print(
    "Zero customers:",
    (future_180 == 0).sum()
)

Positive customers: 655
Zero customers: 55251

In [74]:
future_365 = future_spending_distribution(365)

print(future_365.describe())

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18256\506006491.py:2: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  cutoff = max_olist_date - pd.Timedelta(days=days)

count    21287.000000
mean         4.393234
std         39.600286
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       1596.960000
Name: payment_value, dtype: float64

In [75]:
print(
    "Positive customers:",
    (future_365 > 0).sum()
)

print(
    "Zero customers:",
    (future_365 == 0).sum()
)

Positive customers: 550
Zero customers: 20737

# Revising Task 5 — Construct Spending Features + Next-Order Target

In [76]:
next_order_data = olist_model.copy()

In [77]:
next_order_data = next_order_data.sort_values(
    by=["customer_unique_id", "order_purchase_timestamp"]
).reset_index(drop=True)

In [78]:
print(
    next_order_data[
        [
            "customer_unique_id",
            "order_id",
            "order_purchase_timestamp",
            "payment_value"
        ]
    ].head(10)
)

                 customer_unique_id                          order_id  \
0  0000366f3b9a7992bf8c76cfdf3221e2  e22acc9c116caa3f2b7121bbb380d08e
1  0000b849f77a49e4a4ce2b2a4ca5be3f  3594e05a005ac4d06a72673270ef9ec9
2  0000f46a3911fa3c0805444483337064  b33ec3b699337181488304f362a6b734
3  0000f6ccb0745a6a4b88665a16c9f078  41272756ecddd9a9ed0180413cc22fb6
4  0004aac84e0df4da2b147fca70cf8255  d957021f1127559cd947b62533f484f7
5  0004bd2a26a76fe21f786e4fbd80607f  3e470077b690ea3e3d501cffb5e0c499
6  00050ab1314c0e55a6ca13cf7181fecf  d0028facea13f508e880202d7097a5a1
7  00053a61a98854899e70ed204dd4bafe  44e608f2db00c74a1fe329de44416a4e
8  0005e1862207bf6ccc02e4228effd9a0  ae76bef74b97bcb0b3e355e60d9a6f9c
9  0005ef4cd20d2893f0d9fbd94d3c0d97  01b330808c5819a6a3cb79b72f0b8288

  order_purchase_timestamp  payment_value
0      2018-05-10 10:56:27         141.90
1      2018-05-07 11:11:27          27.19
2      2017-03-10 21:05:03          86.22
3      2017-10-12 20:29:41          43.62
4      2017-11-14 19:45:42         196.89
5      2018-04-05 19:33:16         166.98
6      2018-04-20 12:57:23          35.38
7      2018-02-28 11:15:41         419.18
8      2017-03-04 23:32:12         150.12
9      2018-03-12 15:22:12         129.76

In [79]:
customer_order_counts = (
    next_order_data
    .groupby("customer_unique_id")["order_id"]
    .nunique()
)

In [80]:
print(
    "Total customers:",
    customer_order_counts.shape[0]
)

print(
    "Customers with 2+ orders:",
    (customer_order_counts >= 2).sum()
)

print(
    "Customers with only 1 order:",
    (customer_order_counts == 1).sum()
)

Total customers: 93357
Customers with 2+ orders: 2801
Customers with only 1 order: 90556

In [81]:
next_order_data["PreviousOrderCount"] = (
    next_order_data
    .groupby("customer_unique_id")
    .cumcount()
)

In [82]:
next_order_data["NextOrderSpending"] = (
    next_order_data["payment_value"]
)

In [83]:
next_order_data["CumulativeSpending"] = (
    next_order_data
    .groupby("customer_unique_id")["payment_value"]
    .cumsum()
)

In [84]:
next_order_data["HistoricalSpending"] = (
    next_order_data["CumulativeSpending"]
    - next_order_data["payment_value"]
)

In [85]:
next_order_data["CumulativeItems"] = (
    next_order_data
    .groupby("customer_unique_id")["number_of_items"]
    .cumsum()
)

next_order_data["TotalItems"] = (
    next_order_data["CumulativeItems"]
    - next_order_data["number_of_items"]
)

In [86]:
next_order_data["CumulativeProducts"] = (
    next_order_data
    .groupby("customer_unique_id")["number_of_products"]
    .cumsum()
)

next_order_data["TotalProducts"] = (
    next_order_data["CumulativeProducts"]
    - next_order_data["number_of_products"]
)

In [87]:
next_order_data["CumulativeSellers"] = (
    next_order_data
    .groupby("customer_unique_id")["number_of_sellers"]
    .cumsum()
)

next_order_data["TotalSellers"] = (
    next_order_data["CumulativeSellers"]
    - next_order_data["number_of_sellers"]
)

In [88]:
next_order_data["AverageOrderValue"] = (
    next_order_data["HistoricalSpending"]
    / next_order_data["PreviousOrderCount"]
)

In [89]:
next_order_data["CumulativeFreight"] = (
    next_order_data
    .groupby("customer_unique_id")["total_freight_value"]
    .cumsum()
)

next_order_data["HistoricalFreight"] = (
    next_order_data["CumulativeFreight"]
    - next_order_data["total_freight_value"]
)

In [90]:
next_order_data["AverageFreightValue"] = (
    next_order_data["HistoricalFreight"]
    / next_order_data["PreviousOrderCount"]
)

In [91]:
next_order_data["CumulativeInstallments"] = (
    next_order_data
    .groupby("customer_unique_id")["payment_installments"]
    .cumsum()
)

next_order_data["HistoricalInstallments"] = (
    next_order_data["CumulativeInstallments"]
    - next_order_data["payment_installments"]
)

In [92]:
next_order_data["AverageInstallments"] = (
    next_order_data["HistoricalInstallments"]
    / next_order_data["PreviousOrderCount"]
)

In [93]:
next_order_data["PreviousPurchaseDate"] = (
    next_order_data
    .groupby("customer_unique_id")[
        "order_purchase_timestamp"
    ]
    .shift(1)
)

In [94]:
next_order_data["Recency"] = (
    next_order_data["order_purchase_timestamp"]
    - next_order_data["PreviousPurchaseDate"]
).dt.total_seconds() / (24 * 60 * 60)

In [95]:
next_order_features = next_order_data[
    next_order_data["PreviousOrderCount"] > 0
].copy()

In [96]:
print(
    "Training observations:",
    len(next_order_features)
)

print(
    "Unique customers:",
    next_order_features["customer_unique_id"].nunique()
)

Training observations: 3120
Unique customers: 2801

In [97]:
spending_feature_columns = [
    "Recency",
    "PreviousOrderCount",
    "HistoricalSpending",
    "TotalItems",
    "TotalProducts",
    "TotalSellers",
    "AverageOrderValue",
    "AverageFreightValue",
    "AverageInstallments"
]

In [98]:
spending_features = next_order_features[
    [
        "customer_unique_id",
        *spending_feature_columns,
        "NextOrderSpending"
    ]
].copy()

In [99]:
spending_features.head()

,customer_unique_id,Recency,PreviousOrderCount,HistoricalSpending,TotalItems,TotalProducts,TotalSellers,AverageOrderValue,AverageFreightValue,AverageInstallments,NextOrderSpending
105,004288347e5e88a27ded2bb23747066c,170.724896,1,251.09,1.0,1.0,1.0,251.09,21.10,2.0,103.28
245,00a39521eb40f7012db50455bf083460,10.582361,1,96.47,1.0,1.0,1.0,96.47,26.57,1.0,26.78
308,00cc12a6d8b578b8ebd21ea4e2ae8b27,0.000012,1,44.42,1.0,1.0,1.0,44.42,14.52,1.0,81.78
408,011575986092c30523ecb71ff10cb473,60.252303,1,134.58,1.0,1.0,1.0,134.58,15.58,2.0,80.32
424,011b4adcd54683b480c4d841250a987f,176.951019,1,86.42,1.0,1.0,1.0,86.42,16.93,8.0,149.88

In [100]:
spending_features.isnull().sum()

customer_unique_id     0
Recency                0
PreviousOrderCount     0
HistoricalSpending     0
TotalItems             0
TotalProducts          0
TotalSellers           0
AverageOrderValue      0
AverageFreightValue    0
AverageInstallments    0
NextOrderSpending      0
dtype: int64

In [101]:
print(
    "Spending dataset shape:",
    spending_features.shape
)

Spending dataset shape: (3120, 11)

In [102]:
print(
    spending_features["NextOrderSpending"].describe()
)

count    3120.000000
mean      146.924811
std       161.772273
min        11.560000
25%        59.785000
50%       100.295000
75%       171.297500
max      2621.290000
Name: NextOrderSpending, dtype: float64

In [103]:
print(
    "Zero next-order spending:",
    (
        spending_features["NextOrderSpending"] == 0
    ).sum()
)

Zero next-order spending: 0

In [104]:
print(
    "Positive next-order spending:",
    (
        spending_features["NextOrderSpending"] > 0
    ).sum()
)

Positive next-order spending: 3120

In [105]:
print(
    spending_features[
        [
            "customer_unique_id",
            "Recency",
            "PreviousOrderCount",
            "HistoricalSpending",
            "AverageOrderValue",
            "NextOrderSpending"
        ]
    ].head(10)
)

                   customer_unique_id     Recency  PreviousOrderCount  \
105  004288347e5e88a27ded2bb23747066c  170.724896                   1
245  00a39521eb40f7012db50455bf083460   10.582361                   1
308  00cc12a6d8b578b8ebd21ea4e2ae8b27    0.000012                   1
408  011575986092c30523ecb71ff10cb473   60.252303                   1
424  011b4adcd54683b480c4d841250a987f  176.951019                   1
434  012452d40dafae4df401bced74cdb490  329.559757                   1
445  012a218df8995d3ec3bb221828360c86   42.111354                   1
475  013ef03e0f3f408dd9bf555e4edcdc0a   28.977581                   1
478  013f4353d26bb05dc6652f1269458d8d    3.998356                   1
511  015557c9912277312b9073947804a7ba   38.668600                   1

     HistoricalSpending  AverageOrderValue  NextOrderSpending
105              251.09             251.09             103.28
245               96.47              96.47              26.78
308               44.42              44.42              81.78
408              134.58             134.58              80.32
424               86.42              86.42             149.88
434              155.26             155.26             340.07
445               74.41              74.41            1435.97
475              176.30             176.30              69.07
478              192.35             192.35             164.04
511              242.22             242.22              72.90

In [106]:
print(
    "Total customers:",
    customer_order_counts.shape[0]
)

print(
    "Customers with 2+ orders:",
    (customer_order_counts >= 2).sum()
)

print(
    "Customers with only 1 order:",
    (customer_order_counts == 1).sum()
)

Total customers: 93357
Customers with 2+ orders: 2801
Customers with only 1 order: 90556

In [107]:
print(
    "Spending dataset shape:",
    spending_features.shape
)

Spending dataset shape: (3120, 11)

In [108]:
print(
    spending_features["NextOrderSpending"].describe()
)

count    3120.000000
mean      146.924811
std       161.772273
min        11.560000
25%        59.785000
50%       100.295000
75%       171.297500
max      2621.290000
Name: NextOrderSpending, dtype: float64

In [109]:
print(
    "Zero next-order spending:",
    (spending_features["NextOrderSpending"] == 0).sum()
)

print(
    "Positive next-order spending:",
    (spending_features["NextOrderSpending"] > 0).sum()
)

Zero next-order spending: 0
Positive next-order spending: 3120

In [110]:
spending_features.isnull().sum()

customer_unique_id     0
Recency                0
PreviousOrderCount     0
HistoricalSpending     0
TotalItems             0
TotalProducts          0
TotalSellers           0
AverageOrderValue      0
AverageFreightValue    0
AverageInstallments    0
NextOrderSpending      0
dtype: int64

In [111]:
spending_feature_columns = [
    "Recency",
    "PreviousOrderCount",
    "HistoricalSpending",
    "TotalItems",
    "TotalProducts",
    "TotalSellers",
    "AverageOrderValue",
    "AverageFreightValue",
    "AverageInstallments"
]

In [112]:
X_spending = spending_features[
    spending_feature_columns
].copy()

In [113]:
y_spending = spending_features[
    "NextOrderSpending"
].copy()

In [114]:
print("X shape:", X_spending.shape)
print("y shape:", y_spending.shape)

X shape: (3120, 9)
y shape: (3120,)

In [115]:
print("Features:")
print(X_spending.columns.tolist())

Features:
['Recency', 'PreviousOrderCount', 'HistoricalSpending', 'TotalItems', 'TotalProducts', 'TotalSellers', 'AverageOrderValue', 'AverageFreightValue', 'AverageInstallments']

In [116]:
X_spending.head()

,Recency,PreviousOrderCount,HistoricalSpending,TotalItems,TotalProducts,TotalSellers,AverageOrderValue,AverageFreightValue,AverageInstallments
105,170.724896,1,251.09,1.0,1.0,1.0,251.09,21.10,2.0
245,10.582361,1,96.47,1.0,1.0,1.0,96.47,26.57,1.0
308,0.000012,1,44.42,1.0,1.0,1.0,44.42,14.52,1.0
408,60.252303,1,134.58,1.0,1.0,1.0,134.58,15.58,2.0
424,176.951019,1,86.42,1.0,1.0,1.0,86.42,16.93,8.0

In [117]:
X_spending.dtypes

Recency                float64
PreviousOrderCount       int64
HistoricalSpending     float64
TotalItems             float64
TotalProducts          float64
TotalSellers           float64
AverageOrderValue      float64
AverageFreightValue    float64
AverageInstallments    float64
dtype: object

In [118]:
y_spending.head()

105    103.28
245     26.78
308     81.78
408     80.32
424    149.88
Name: NextOrderSpending, dtype: float64

In [119]:
y_spending.describe()

count    3120.000000
mean      146.924811
std       161.772273
min        11.560000
25%        59.785000
50%       100.295000
75%       171.297500
max      2621.290000
Name: NextOrderSpending, dtype: float64

In [120]:
print("Missing values in X:")
print(X_spending.isnull().sum())

print("\nMissing values in y:")
print(y_spending.isnull().sum())

Missing values in X:
Recency                0
PreviousOrderCount     0
HistoricalSpending     0
TotalItems             0
TotalProducts          0
TotalSellers           0
AverageOrderValue      0
AverageFreightValue    0
AverageInstallments    0
dtype: int64

Missing values in y:
0

In [121]:
print("X columns:")
print(X_spending.columns.tolist())

print("\nTarget:")
print(y_spending.name)

X columns:
['Recency', 'PreviousOrderCount', 'HistoricalSpending', 'TotalItems', 'TotalProducts', 'TotalSellers', 'AverageOrderValue', 'AverageFreightValue', 'AverageInstallments']

Target:
NextOrderSpending

In [122]:
print("X shape:", X_spending.shape)
print("y shape:", y_spending.shape)
print(X_spending.isnull().sum())
print(y_spending.isnull().sum())

X shape: (3120, 9)
y shape: (3120,)
Recency                0
PreviousOrderCount     0
HistoricalSpending     0
TotalItems             0
TotalProducts          0
TotalSellers           0
AverageOrderValue      0
AverageFreightValue    0
AverageInstallments    0
dtype: int64
0

# Customer-Level Train/Test Split

In [123]:
customer_ids = spending_features[
    "customer_unique_id"
].copy()

In [124]:
print("Total observations:", len(customer_ids))
print("Unique customers:", customer_ids.nunique())

Total observations: 3120
Unique customers: 2801

In [125]:
from sklearn.model_selection import train_test_split
unique_customers = customer_ids.unique()

train_customers, test_customers = train_test_split(
    unique_customers,
    test_size=0.20,
    random_state=42
)

In [126]:
train_mask = customer_ids.isin(train_customers)
test_mask = customer_ids.isin(test_customers)

In [127]:
X_train_spending = X_spending[train_mask].copy()
X_test_spending = X_spending[test_mask].copy()

y_train_spending = y_spending[train_mask].copy()
y_test_spending = y_spending[test_mask].copy()

In [128]:
print("X_train shape:", X_train_spending.shape)
print("X_test shape:", X_test_spending.shape)

print("y_train shape:", y_train_spending.shape)
print("y_test shape:", y_test_spending.shape)

X_train shape: (2499, 9)
X_test shape: (621, 9)
y_train shape: (2499,)
y_test shape: (621,)

In [129]:
print(
    "Training customers:",
    len(train_customers)
)

print(
    "Testing customers:",
    len(test_customers)
)

Training customers: 2240
Testing customers: 561

In [130]:
customer_overlap = set(train_customers).intersection(
    set(test_customers)
)

print(
    "Customers appearing in both sets:",
    len(customer_overlap)
)

Customers appearing in both sets: 0

In [131]:
print(
    "Training observations:",
    len(X_train_spending)
)

print(
    "Testing observations:",
    len(X_test_spending)
)

print(
    "Total observations:",
    len(X_train_spending) + len(X_test_spending)
)

Training observations: 2499
Testing observations: 621
Total observations: 3120

In [132]:
print("Training target:")
print(y_train_spending.describe())

Training target:
count    2499.000000
mean      144.117711
std       158.501146
min        11.560000
25%        60.000000
50%        99.540000
75%       168.425000
max      2621.290000
Name: NextOrderSpending, dtype: float64

In [133]:
print("\nTesting target:")
print(y_test_spending.describe())

Testing target:
count     621.000000
mean      158.221014
std       173.994091
min        14.780000
25%        59.500000
50%       103.260000
75%       190.460000
max      1391.790000
Name: NextOrderSpending, dtype: float64

In [134]:
print(
    "Maximum training spending:",
    y_train_spending.max()
)

print(
    "Maximum testing spending:",
    y_test_spending.max()
)

Maximum training spending: 2621.29
Maximum testing spending: 1391.79

In [135]:
print("X_train shape:", X_train_spending.shape)
print("X_test shape:", X_test_spending.shape)

X_train shape: (2499, 9)
X_test shape: (621, 9)

In [136]:
print("Training customers:", len(train_customers))
print("Testing customers:", len(test_customers))

Training customers: 2240
Testing customers: 561

In [ ]:
print("Customers appearing in both sets:",len(customer_overlap))

Customers appearing in both sets: 0

In [138]:
print(y_train_spending.describe())
print(y_test_spending.describe())

count    2499.000000
mean      144.117711
std       158.501146
min        11.560000
25%        60.000000
50%        99.540000
75%       168.425000
max      2621.290000
Name: NextOrderSpending, dtype: float64
count     621.000000
mean      158.221014
std       173.994091
min        14.780000
25%        59.500000
50%       103.260000
75%       190.460000
max      1391.790000
Name: NextOrderSpending, dtype: float64

# Task 6.3 - Train Random Forest Regressor